name: Generate Snake Animation

on:
workflow_dispatch:
schedule:
- cron: "0 */12 * * *"

permissions:
contents: write

jobs:
build:
runs-on: ubuntu-latest

```
steps:
  - name: Generate snake
    uses: Platane/snk@v3
    with:
      github_user_name: ravigohel142996
      outputs: |
        dist/github-contribution-grid-snake.svg

  - name: Push snake
    uses: crazy-max/ghaction-github-pages@v3
    with:
      target_branch: output
      build_dir: dist
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
